import type { Metadata } from "next";
import { Sulphur_Point } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import PageTransitionEffect from "@/components/PageTransitionEffect";

const inter = Sulphur_Point({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`overflow-x-hidden ${inter.className}`}>
        <Header />
        <PageTransitionEffect>{children}</PageTransitionEffect>
      </body>
    </html>
  );
}
